name: payguard

services:

  postgres:
    image: postgres:17
    container_name: payguard-postgres

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: payguard
      POSTGRES_PASSWORD: payguard

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "payguard", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - payguard-network

  redis:
    image: redis:8
    container_name: payguard-redis

    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

    ports:
      - "6379:6379"

    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - payguard-network

  kafka:
    image: apache/kafka:4.0.0
    container_name: payguard-kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKER://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - payguard-network

  kafka-console:
    image: docker.redpanda.com/redpandadata/console:v3.9.0
    container_name: payguard-kafka-console

    depends_on:
      - kafka

    environment:
      KAFKA_BROKERS: kafka:29092

    ports:
      - "8085:8080"

    networks:
      - payguard-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    container_name: payguard-keycloak

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD:?Set KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD in .env}
      PAYGUARD_BOOTSTRAP_ADMIN_EMAIL: ${PAYGUARD_BOOTSTRAP_ADMIN_EMAIL:-platform-admin@payguard.local}
      PAYGUARD_BOOTSTRAP_ADMIN_PASSWORD: ${PAYGUARD_BOOTSTRAP_ADMIN_PASSWORD:?Set PAYGUARD_BOOTSTRAP_ADMIN_PASSWORD in .env}
      PAYMENT_SERVICE_CLIENT_SECRET: ${PAYMENT_SERVICE_CLIENT_SECRET:?Set PAYMENT_SERVICE_CLIENT_SECRET in .env}
      NOTIFICATION_SERVICE_CLIENT_SECRET: ${NOTIFICATION_SERVICE_CLIENT_SECRET:?Set NOTIFICATION_SERVICE_CLIENT_SECRET in .env}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: payguard
      KC_DB_PASSWORD: payguard

      KC_HEALTH_ENABLED: "true"

    ports:
      - "8080:8080"

    volumes:
      - ./docker/keycloak/realms/realm-export.json:/opt/keycloak/data/import/payguard-realm.json:ro

    command:
      - start-dev
      - --import-realm

    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - payguard-network


  tempo:
    image: grafana/tempo:2.8.1
    container_name: payguard-tempo

    command:
      - "-config.file=/etc/tempo/tempo.yml"

    volumes:
      - ./docker/observability/tempo/tempo.yml:/etc/tempo/tempo.yml

    ports:
      - "3200:3200"
      - "4317"

    networks:
      - payguard-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.130.1
    container_name: payguard-otel-collector

    command:
      - "--config=/etc/otelcol/otel-collector.yml"

    volumes:
      - ./docker/observability/otel/otel-collector.yml:/etc/otelcol/otel-collector.yml

    ports:
      - "4317:4317"
      - "4318:4318"

    depends_on:
      - tempo

    networks:
      - payguard-network

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: payguard-prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    volumes:
      - ./docker/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    depends_on:
      - tempo

    networks:
      - payguard-network

  loki:
    image: grafana/loki:3.5.5

    container_name: payguard-loki

    command:
      - -config.file=/etc/loki/loki.yml

    volumes:

      - ./docker/observability/loki/loki.yml:/etc/loki/loki.yml

      - loki-data:/loki

    ports:
      - "3100:3100"

    networks:
      - payguard-network

  alloy:
    image: grafana/alloy:v1.10.2

    container_name: payguard-alloy

    command:
      - run
      - /etc/alloy/config.alloy

    volumes:
      - ./docker/observability/alloy/config.alloy:/etc/alloy/config.alloy

      - ./logs:/var/log/payguard

    depends_on:
      - loki

    ports:
      - "12345:12345"

    networks:
      - payguard-network

  grafana:
    image: grafana/grafana:12.1.0
    container_name: payguard-grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana-data:/var/lib/grafana

      - ./docker/observability/grafana/grafana.ini:/etc/grafana/grafana.ini

      - ./docker/observability/grafana/provisioning:/etc/grafana/provisioning

    depends_on:
      - prometheus
      - tempo
      - loki

    networks:
      - payguard-network

volumes:
  postgres-data:
  kafka-data:
  grafana-data:
  loki-data:

networks:
  payguard-network:
    driver: bridge
