{
 "title": "PayGuard Logs",
 "tags": [
  "payguard",
  "logs",
  "observability",
  "debugging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   { "name": "level", "label": "Level", "query": "TRACE,DEBUG,INFO,WARN,ERROR" },
   { "name": "search", "label": "Search", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Logs/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} | json | level =~ \"$level\" |~ \"$search\"[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service_name=~\"$service_name\"} | json |~ \"$search\"[$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=~\"$service_name\"} | json | level =~ \"$level\" |~ \"$search\""
    }
   ]
  }
 ]
}