spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s

  lifecycle:
    timeout-per-shutdown-phase: 30s

  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true

          httpclient:
            connect-timeout: 5000
            response-timeout: 30s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/payguard

gateway:
  rate-limit:
    registration:
      identity:
        replenish-rate: ${USER_REGISTRATION_REPLENISH_RATE:1}
        burst-capacity: ${USER_REGISTRATION_BURST_CAPACITY:5}
        requested-tokens: 1
      verification-email:
        replenish-rate: ${VERIFICATION_EMAIL_REPLENISH_RATE:1}
        burst-capacity: ${VERIFICATION_EMAIL_BURST_CAPACITY:3}
        requested-tokens: 1

  routes:
    user-service:
      uri: ${USER_SERVICE_URL:http://localhost:8081}

    keycloak:
      uri: ${KEYCLOAK_URL:http://localhost:8080}

server:
  port: 8084

  shutdown: graceful

  forward-headers-strategy: framework

  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/html

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

  endpoint:
    gateway:
      access: read-only

    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - gateway



logging:
  file:
    name: ${LOG_DIR:logs}/${spring.application.name}.log
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"

  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.FilteringWebHandler: TRACE
    org.springframework.cloud.gateway.filter: TRACE

    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
    io.opentelemetry.exporter.otlp: DEBUG
    io.opentelemetry.sdk.autoconfigure: DEBUG
